### ISSUE TITLE
爬虫貌似失效了

### ISSUE THREAD

**Issue by zlgxzswjy** [0xbug/Hawkeye#30]
我这是直接执行spider.py，都会提示登录失败，账号密码肯定没错，而且我把spider.py里的链接直接复制出来，是可以看到执行结果的，但是爬虫执行时就不行，会不会是爬虫被git封了啊

**Comment by 0xbug** [comment]
我这边测试没问题，你可以在spider.py 把响应打印出来看看

**Comment by zlgxzswjy** [comment]
我给spider.py提供了参数 1 2 ，返回登录失败，响应中也确实有错误信息:"We could not perform this search"，提供参数1 1时没有提示登录失败，但是也没有响应内容

**Comment by 0xbug** [comment]
是不是关键词有问题呢

**Comment by zlgxzswjy** [comment]
我这边试了一下，关键字直接在git上搜是可以的，直接带到链接里也没问题，准备再调试下看看什么情况，您如果有新的发现，也辛苦发布一下，感谢感谢

**Comment by zlgxzswjy** [comment]
你好，我在create_session()函数里的“session.post('https://github.com/session', data=post_form)”处，打印了这个提交账号密码的返回信息，看到页面里有提示“<p>Your browser did something unexpected. Please contact us if the problem persists.</p>”,不知道是什么情况，git识别出这事爬虫给ban了么？

**Comment by 0xbug** [comment]
添加个UserAgent试试 在2017年12月06日 09:25 ，zlgxzswjy写道： 你好，我在create_session()函数里的“session.post('https://github.com/session', data=post_form)”处，打印了这个提交账号密码的返回信息，看到页面里有提示“ Your browser did something unexpected. Please contact us if the problem persists.”,不知道是什么情况，git识别出这事爬虫给ban了么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
